---
title: "spatial estimation"
output: html_document
---

```{r load libraries, echo = FALSE}
library(StanHeaders)
library(rstan)
library(ggplot2)
library(brms)
library(dplyr)
library(rjags)
library(MASS)  # need for mvrnorm
library(MCMCpack) # need for rwish
library(ggmap)
library(tidyr)
library(ggforce)
library(RColorBrewer)
```

## R Markdown

load data

```{r}
#path = "E:/Desktop/2022 Spring/6780/Project/6780_project/data_with_coordinates.csv"
path = "/Users/felicityj/Documents/GitHub/6780_project/data_with_coordinates.csv"
data = data.frame(read.csv(path))
data_with_ct <- data[!is.na(data['census_tract']),]
dim(data); dim(data_with_ct)
```

## bivariate normal on real data

```{r}
N <- 10000
coord_df <- subset(data_with_ct, select=c("Latitude", "Longitude"))
coord_df <- as.data.frame(coord_df[1:N,])
coord <- data.matrix(coord_df)

```


# Just Manhattan
```{r}
df.manhattan <- data_with_ct[data_with_ct$Borough == "Manhattan",]
coord_manhattan <- subset(df.manhattan, select=c("Latitude", "Longitude"))
dim(coord_manhattan)
coord_manhattan <- as.data.frame(coord_manhattan)
coord_manhattan <- data.matrix(coord_manhattan)
mixture_Gaussians(coord_manhattan)

```


## varying covariance matrix
```{r}
mixture_Gaussians <- function(coord){
  xi <- as.vector(apply(coord, 2, median))
  rng_coord <- apply(coord, 2, range)
  R1 <- rng_coord[2,1]-rng_coord[1,1]
  R2 <- rng_coord[2,2]-rng_coord[1,2]
  kappa <- matrix(c(1/R1^2,0,0,1/R2^2),nrow=2)
  beta <- matrix(c(R1^2/10,0,0,R2^2/10),nrow=2)
  g <- 2
  alpha <- 6
  for (K in 2:3){
    onesRepNclust <- rep(1,K)
    data = list(y=coord,N=N,xi=xi,kappa=kappa,alpha=alpha, beta=beta,K=K, onesRepNclust=onesRepNclust)
    muOfGaussian.name <- sprintf("muOfGaussian[%s,%s]",rep(1:K,each=2),rep(1:2,times=K))
    cov.name <- sprintf("cov[%s,%s,%s]",rep(1:2,each=2),rep(1:2,times=2),rep(1:K,each=4))
    pk.name <- sprintf("pk[%s]",seq(1:K))
    corr.name <- sprintf("corr[%s]",seq(1:K))
    name <- c(muOfGaussian.name, cov.name, pk.name, corr.name)
    multNorm.mcmc <- jags.model("spatial_varying_tau.bug",data=data,n.chains = 4, n.adapt=1000, quiet=FALSE)
    nthin = 5
    multNorm.coda = coda.samples(multNorm.mcmc,name,500*nthin, thin = nthin)
    multnorm.dic = dic.samples(multNorm.mcmc,n.iter=500,thin=1)
    mat.coda <-as.matrix(multNorm.coda)
    mean.coda <- apply(mat.coda, 2, mean)
    write.csv(mean.coda, file=paste(K,"_posterior_Manhattan.csv",sep=""), row.names = T)
    mat.dic <- sum(multnorm.dic$deviance)+sum(multnorm.dic$penalty)
    write.csv(mat.dic, file=paste(K,"_dic_Manhattan.csv", sep=""),row.names = T)
  }

}
#inits=function(){list( mu=mvrnorm(N,xi,matrix(c(10,0,0,10),nrow=2) ),
                       #tau = rwish(6,matrix(c(.02,0,0,.04),nrow=2)))}
```

```{r}
mu=mvrnorm(N,xi,matrix(c(10,0,0,10),nrow=2))
```

```{r}
K<-2
muOfGaussian.name <- sprintf("muOfGaussian[%s,%s]",rep(1:K,each=2),rep(1:2,times=K))
cov.name <- sprintf("cov[%s,%s,%s]",rep(1:2,each=2),rep(1:2,times=2),rep(1:K,each=4))
pk.name <- sprintf("pk[%s]",seq(1:K))
corr.name <- sprintf("corr[%s]",seq(1:K))
name <- c(muOfGaussian.name, cov.name, pk.name, corr.name)
t1 = proc.time()
multNorm.mcmc <- jags.model("spatial_varying_tau.bug",data=data,n.chains = 3, n.adapt=1000, quiet=FALSE)
nthin = 5
multNorm.coda = coda.samples(multNorm.mcmc,name,500*nthin, thin = nthin)
t2 = proc.time()
```


```{r}
t2-t1
summary(multNorm.coda,digits=2)
```
```{r}
mat.coda <-as.matrix(multNorm.coda)
mean.coda <- apply(mat.coda, 2, mean)
```




```{r}
post_stats <- as.data.frame(read.table("3_posterior.csv", row.names = 1, sep = ","))
a <- c()
b <- c()
angle_x <- c()
mu_x <- c()
mu_y <- c()
for (k in 1:K){
  mux.name.k <- sprintf("muOfGaussian[%s,%s]",k,1)
  muy.name.k <- sprintf("muOfGaussian[%s,%s]",k,2)
  mu_x <- append(mu_x, mean.coda[mux.name.k])
  mu_y <- append(mu_y, mean.coda[muy.name.k])
  cov.name.k <- sprintf("cov[%s,%s,%s]",rep(1:2,each=2),rep(1:2,times=2),k)
  cov.k = matrix(mean.coda[cov.name.k], nrow = 2)
  eig_cov.k <- eigen(cov.k)
  a <- append(a, sqrt(eig_cov.k$values[1]))
  b <- append(b, sqrt(eig_cov$values[2]))
  angle_x <- append(angle_x, acos(eig_cov$vectors[1,1]))
}


cols <- brewer.pal(4,'Set2')

p <- ggplot(coord_df, aes(x=Latitude, y=Longitude)) + geom_point(size = 1, alpha=0.6, colour = '#56B4E9')

for (k in 1:K){
  p <- p + geom_point(aes(x=mu_x[k], y=mu_y[k]), size = 2, alpha=1.0, colour = cols[k])
  print(k)
  p <- p + geom_ellipse(aes(x0=mu_x[k], y0=mu_y[k], a=a[k],b=b[k], angle = angle_x[k], color=cols[k]))
}

# p <- p + theme(legend.position="none")
p


for (k in 1:K){
  p <- p + geom_point(aes_string(x=mu_x[k], y=mu_y[k]), size = 2, alpha=1.0, color = cols[k])
  print(k)
  #p <- p + geom_ellipse(aes(x0=mu_x[k], y0=mu_y[k], a=a[k],b=b[k], angle = angle_x[k], color=cols[k]))
  loop_ellipse_input = 
    paste("geom_ellipse(aes(x0=",mu_x[k], ", y0=",mu_y[k],", a=", a[k],",b=",b[k],", angle = ",angle_x[k], "))", sep="")
  # p <- p + geom_ellipse(aes_string(x0="mu_x[k]", y0="mu_y[k]", a="a[k]",b="b[k]", angle = "angle_x[k]", color=cols[k]))
  p <- p+eval(parse(text= loop_ellipse_input))
  print(p)
  #Sys.sleep(2)
}

```

# Plot ellipse given posterior
```{r}
post_stats <- as.data.frame(read.table("3_posterior.csv", row.names = 1, sep = ","))
K <- 3
a <- c()
b <- c()
angle_x <- c()
mu_x <- c()
mu_y <- c()
for (k in 1:K){
  mux.name.k <- sprintf("muOfGaussian[%s,%s]",k,1)
  muy.name.k <- sprintf("muOfGaussian[%s,%s]",k,2)
  mu_x <- append(mu_x, post_stats[mux.name.k,])
  mu_y <- append(mu_y, post_stats[muy.name.k,])
  cov.name.k <- sprintf("cov[%s,%s,%s]",rep(1:2,each=2),rep(1:2,times=2),k)
  cov.k = matrix(post_stats[cov.name.k,], nrow = 2)
  eig_cov.k <- eigen(cov.k)
  a <- append(a, sqrt(eig_cov.k$values[1]))
  b <- append(b, sqrt(eig_cov.k$values[2]))
  angle_x <- append(angle_x, acos(eig_cov.k$vectors[1,1]))
}


cols <- brewer.pal(4,'Set2')
cols <- c("red", "blue", "black")
p <- ggplot(coord_df, aes(x=Latitude, y=Longitude)) + geom_point(size = 1, alpha=0.6, colour = '#56B4E9')

p <- p + geom_point(aes(x=mu_x[1], y=mu_y[1]), size = 2, alpha=1.0, colour = "black")
p <- p + geom_ellipse(aes(x0=mu_x[1], y0=mu_y[1], a=a[k],b=b[2], angle = angle_x[2], color="k"))
p <- p + geom_point(aes(x=mu_x[2], y=mu_y[2]), size = 2, alpha=1.0, colour = "black")
p <- p + geom_ellipse(aes(x0=mu_x[2], y0=mu_y[2], a=a[2],b=b[2], angle = angle_x[2], color="black"))
p
ggsave("3mixture.pdf")
# p <- p + theme(legend.position="none")



for (k in 1:K){
  p <- p + geom_point(aes_string(x=mu_x[k], y=mu_y[k]), size = 2, alpha=1.0, color = cols[k])
  print(k)
  #p <- p + geom_ellipse(aes(x0=mu_x[k], y0=mu_y[k], a=a[k],b=b[k], angle = angle_x[k], color=cols[k]))
  loop_ellipse_input = 
    paste("geom_ellipse(aes(x0=",mu_x[k], ", y0=",mu_y[k],", a=", a[k],",b=",b[k],", angle = ",angle_x[k], "))", sep="")
  # p <- p + geom_ellipse(aes_string(x0="mu_x[k]", y0="mu_y[k]", a="a[k]",b="b[k]", angle = "angle_x[k]", color=cols[k]))
  p <- p+eval(parse(text= loop_ellipse_input))
  print(p)
  #Sys.sleep(2)
}
ggsave("3mixture.pdf")

```

```{r}
gelman.diag(multNorm.coda)
effectiveSize(multNorm.coda)

par(mfrow = c(3, 4))
plot(multNorm.coda, auto.layout = FALSE)

par(mfrow=c(2,3))
gelman.plot(multNorm.coda,auto.layout = FALSE)

```













